#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-nginx-deployment
  labels:
    app: default-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: default-nginx
  template:
    metadata:
      labels:
        app: default-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
---
#Service
apiVersion: v1
kind: Service
metadata:
  name: default-nginx-service
spec:
  selector:
    app: default-nginx
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
